### ISSUE TITLE
kiss_icp_pipeline can not find

### ISSUE THREAD

**Issue by gongjun136** [PRBonn/kiss-icp#82] opened 2023-02-27 08:46 UTC
hi, I have install kiss-icp,but can not find command:
![image](https://user-images.githubusercontent.com/73570451/221515661-2c0a67dd-630e-4684-84d5-267d6bd8e574.png)

**Comment by benemer** [comment] 2023-02-27 09:02
Duplicate of https://github.com/PRBonn/kiss-icp/issues/28

**Closed by benemer** 2023-02-27 09:02 UTC
