### ISSUE TITLE
Question about VoxelHash function for Vector3i

### ISSUE THREAD

**Issue by zzodo** [PRBonn/kiss-icp#227] opened 2023-09-27 09:11 UTC
Hi, thank you for sharing your work

I have question about the hash function in [this line](https://github.com/PRBonn/kiss-icp/blob/523fd58babb9e12a3883a30758f22e071555f7d5/cpp/kiss_icp/core/VoxelHashMap.hpp#L51).

It seems that the hash numbers, `73856093`, `19349669` and `83492791`, came from this paper [Optimized Spatial Hashing for Collision Detection of Deformable Objects](http://www.beosil.com/download/CollisionDetectionHashing_VMV03.pdf), but the second hash key `19349669` does not match with the `19349663` which described as an example in Section 4.1.

So is there another theory going on the hash function? or just typo?

**Comment by nachovizzo** [comment] 2023-09-27 10:45
Duplicate of #178

**Closed by nachovizzo** 2023-09-27 10:45 UTC
